pipeline {
	
	agent any

	environment {
          TEAM = 'Lateblumer88'
          PROJECT = 'yoyowallet-devops-interview'
          VERSION = '1.0.0'
    }
    
	stages {
		
		stage ('Checkout') {
			steps {
				checkout([
					$class: 'GitSCM',
					branches: [[name: "*/release/${env.VERSION}"]],
					doGenerateSubmoduleConfigurations: false, 
					extensions: [[$class: 'LocalBranch']], 
					submoduleCfg: [], 
					userRemoteConfigs: [[credentialsId: 'Github-credential', url: "https://github.com/${env.TEAM}/${env.PROJECT}.git"]]
              ])
			}
		}

        stage ('Docker container'){

            steps {

                 script {
			
                     sh "docker build . -t transaction-api -f /var/lib/jenkins/workspace/YOYO-devops-interview-auth-api/transaction-api/Dockerfile"
                     //sh "docker run -d --link cfao_core_services --name cfao_cms -p 8431:8431 cfao_cms"

				}

            }

        }

	}
	
}
